In [88]:
!pip3 install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy<2,>=1.22.4 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas) (1.24.3)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas) (2026.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install --upgrade pip' command.

In [89]:
import pandas as pd

In [90]:
column_names = ['order_id', 'order_date', 'order_customer_id', 'order_status']

In [91]:
orders = pd.read_csv('/Users/amisha/Desktop/Data_engineering/data/retail_db/orders/part-00000',
    header=None,
    names=column_names)

In [92]:
orders.head(5)

   order_id             order_date  order_customer_id     order_status
0         1  2013-07-25 00:00:00.0              11599           CLOSED
1         2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2         3  2013-07-25 00:00:00.0              12111         COMPLETE
3         4  2013-07-25 00:00:00.0               8827           CLOSED
4         5  2013-07-25 00:00:00.0              11318         COMPLETE

In [93]:
orders.columns

Index(['order_id', 'order_date', 'order_customer_id', 'order_status'], dtype='object')

In [94]:
orders.query?

Signature: orders.query(expr: 'str', *, inplace: 'bool' = False, **kwargs) -> 'DataFrame | None'
Docstring:
Query the columns of a DataFrame with a boolean expression.

Parameters
----------
expr : str
    The query string to evaluate.

    You can refer to variables
    in the environment by prefixing them with an '@' character like
    ``@a + b``.

    You can refer to column names that are not valid Python variable names
    by surrounding them in backticks. Thus, column names containing spaces
    or punctuations (besides underscores) or starting with digits must be
    surrounded by backticks. (For example, a column named "Area (cm^2)" would
    be referenced as ```Area (cm^2)```). Column names which are Python keywords
    (like "list", "for", "import", etc) cannot be used.

    For example, if one of your columns is called ``a a`` and you want
    to sum it with ``b``, your query should be ```a a` + b``.

inplace : bool
    Whether to modify the DataFrame rather than creating a new one.
**kwargs
    See the documentation for :func:`eval` for complete details
    on the keyword arguments accepted by :meth:`DataFrame.query`.

Returns
-------
DataFrame or None
    DataFrame resulting from the provided query expression or
    None if ``inplace=True``.

See Also
--------
eval : Evaluate a string describing operations on
    DataFrame columns.
DataFrame.eval : Evaluate a string describing operations on
    DataFrame columns.

Notes
-----
The result of the evaluation of this expression is first passed to
:attr:`DataFrame.loc` and if that fails because of a
multidimensional key (e.g., a DataFrame) then the result will be passed
to :meth:`DataFrame.__getitem__`.

This method uses the top-level :func:`eval` function to
evaluate the passed query.

The :meth:`~pandas.DataFrame.query` method uses a slightly
modified Python syntax by default. For example, the ``&`` and ``|``
(bitwise) operators have the precedence of their boolean cousins,
:keyword:`and` and :keyword:`or`. This *is* syntactically valid Python,
however the semantics are different.

You can change the semantics of the expression by passing the keyword
argument ``parser='python'``. This enforces the same semantics as
evaluation in Python space. Likewise, you can pass ``engine='python'``
to evaluate an expression using Python itself as a backend. This is not
recommended as it is inefficient compared to using ``numexpr`` as the
engine.

The :attr:`DataFrame.index` and
:attr:`DataFrame.columns` attributes of the
:class:`~pandas.DataFrame` instance are placed in the query namespace
by default, which allows you to treat both the index and columns of the
frame as a column in the frame.
The identifier ``index`` is used for the frame index; you can also
use the name of the index to identify it in a query. Please note that
Python keywords may not be used as identifiers.

For further details and examples see the ``query`` documentation in
:ref:`indexing <indexing.query>`.

*Backtick quoted variables*

Backtick quoted variables are parsed as literal Python code and
are converted internally to a Python valid identifier.
This can lead to the following problems.

During parsing a number of disallowed characters inside the backtick
quoted string are replaced by strings that are allowed as a Python identifier.
These characters include all operators in Python, the space character, the
question mark, the exclamation mark, the dollar sign, and the euro sign.
For other characters that fall outside the ASCII range (U+0001..U+007F)
and those that are not further specified in PEP 3131,
the query parser will raise an error.
This excludes whitespace different than the space character,
but also the hashtag (as it is used for comments) and the backtick
itself (backtick can also not be escaped).

In a special case, quotes that make a pair around a backtick can
confuse the parser.
For example, ```it's` > `that's``` will raise an error,
as it forms a quoted string (``'s > `that'``) with a backtick inside.

See also the Python documentation about lexical analysis
(https://docs.python.org/3/reference/lexical_analysis.html)
in combination with the source code in :mod:`pandas.core.computation.parsing`.

Examples
--------
>>> df = pd.DataFrame({'A': range(1, 6),
...                    'B': range(10, 0, -2),
...                    'C C': range(10, 5, -1)})
>>> df
   A   B  C C
0  1  10   10
1  2   8    9
2  3   6    8
3  4   4    7
4  5   2    6
>>> df.query('A > B')
   A  B  C C
4  5  2    6

The previous expression is equivalent to

>>> df[df.A > df.B]
   A  B  C C
4  5  2    6

For columns with spaces in their name, you can use backtick quoting.

>>> df.query('B == `C C`')
   A   B  C C
0  1  10   10

The previous expression is equivalent to

>>> df[df.B == df['C C']]
   A   B  C C
0  1  10   10
File:      /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/frame.py
Type:      method

In [95]:
orders['order_status'].unique()

array(['CLOSED', 'PENDING_PAYMENT', 'COMPLETE', 'PROCESSING',
       'PAYMENT_REVIEW', 'PENDING', 'ON_HOLD', 'CANCELED',
       'SUSPECTED_FRAUD'], dtype=object)

In [96]:
orders.query('order_status == "COMPLETE"')

       order_id             order_date  order_customer_id order_status
2             3  2013-07-25 00:00:00.0              12111     COMPLETE
4             5  2013-07-25 00:00:00.0              11318     COMPLETE
5             6  2013-07-25 00:00:00.0               7130     COMPLETE
6             7  2013-07-25 00:00:00.0               4530     COMPLETE
14           15  2013-07-25 00:00:00.0               2568     COMPLETE
...         ...                    ...                ...          ...
68875     68876  2014-07-06 00:00:00.0               4124     COMPLETE
68877     68878  2014-07-08 00:00:00.0               6753     COMPLETE
68878     68879  2014-07-09 00:00:00.0                778     COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117     COMPLETE
68882     68883  2014-07-23 00:00:00.0               5533     COMPLETE

[22899 rows x 4 columns]

In [97]:
orders.query('order_status == ("COMPLETE","CLOSED")')

       order_id             order_date  order_customer_id order_status
0             1  2013-07-25 00:00:00.0              11599       CLOSED
2             3  2013-07-25 00:00:00.0              12111     COMPLETE
3             4  2013-07-25 00:00:00.0               8827       CLOSED
4             5  2013-07-25 00:00:00.0              11318     COMPLETE
5             6  2013-07-25 00:00:00.0               7130     COMPLETE
...         ...                    ...                ...          ...
68875     68876  2014-07-06 00:00:00.0               4124     COMPLETE
68877     68878  2014-07-08 00:00:00.0               6753     COMPLETE
68878     68879  2014-07-09 00:00:00.0                778     COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117     COMPLETE
68882     68883  2014-07-23 00:00:00.0               5533     COMPLETE

[30455 rows x 4 columns]

In [98]:
orders.query('order_status == "COMPLETE" or order_status == "CLOSED"')

       order_id             order_date  order_customer_id order_status
0             1  2013-07-25 00:00:00.0              11599       CLOSED
2             3  2013-07-25 00:00:00.0              12111     COMPLETE
3             4  2013-07-25 00:00:00.0               8827       CLOSED
4             5  2013-07-25 00:00:00.0              11318     COMPLETE
5             6  2013-07-25 00:00:00.0               7130     COMPLETE
...         ...                    ...                ...          ...
68875     68876  2014-07-06 00:00:00.0               4124     COMPLETE
68877     68878  2014-07-08 00:00:00.0               6753     COMPLETE
68878     68879  2014-07-09 00:00:00.0                778     COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117     COMPLETE
68882     68883  2014-07-23 00:00:00.0               5533     COMPLETE

[30455 rows x 4 columns]

Here are the tasks related to aggregations.

Get count by order status.

Get count by order month and then by order status. 

We need to generate order month using order date using apply on dataframe.

orders.apply(lambda order: order.order_date[:7], axis=1)

In [99]:
help(orders.apply)

Help on method apply in module pandas.core.frame:

apply(func: 'AggFuncType', axis: 'Axis' = 0, raw: 'bool' = False, result_type: "Literal['expand', 'reduce', 'broadcast'] | None" = None, args=(), by_row: "Literal[False, 'compat']" = 'compat', **kwargs) method of pandas.core.frame.DataFrame instance
    Apply a function along an axis of the DataFrame.

    Objects passed to the function are Series objects whose index is
    either the DataFrame's index (``axis=0``) or the DataFrame's columns
    (``axis=1``). By default (``result_type=None``), the final return type
    is inferred from the return type of the applied function. Otherwise,
    it depends on the `result_type` argument.

    Parameters
    ----------
    func : function
        Function to apply to each column or row.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis along which the function is applied:

        * 0 or 'index': apply function to each column.
        * 1 or 'columns': apply function to each row.

    raw : bool, default False
        Determines if row or column is passed as a Series or ndarray object:

        * ``False`` : passes each row or column as a Series to the
          function.
        * ``True`` : the passed function will receive ndarray objects
          instead.
          If you are just applying a NumPy reduction function this will
          achieve much better performance.

    result_type : {'expand', 'reduce', 'broadcast', None}, default None
        These only act when ``axis=1`` (columns):

        * 'expand' : list-like results will be turned into columns.
        * 'reduce' : returns a Series if possible rather than expanding
          list-like results. This is the opposite of 'expand'.
        * 'broadcast' : results will be broadcast to the original shape
          of the DataFrame, the original index and columns will be
          retained.

        The default behaviour (None) depends on the return value of the
        applied function: list-like results will be returned as a Series
        of those. However if the apply function returns a Series these
        are expanded to columns.
    args : tuple
        Positional arguments to pass to `func` in addition to the
        array/series.
    by_row : False or "compat", default "compat"
        Only has an effect when ``func`` is a listlike or dictlike of funcs
        and the func isn't a string.
        If "compat", will if possible first translate the func into pandas
        methods (e.g. ``Series().apply(np.sum)`` will be translated to
        ``Series().sum()``). If that doesn't work, will try call to apply again with
        ``by_row=True`` and if that fails, will call apply again with
        ``by_row=False`` (backward compatible).
        If False, the funcs will be passed the whole Series at once.

        .. versionadded:: 2.1.0
    **kwargs
        Additional keyword arguments to pass as keywords arguments to
        `func`.

    Returns
    -------
    Series or DataFrame
        Result of applying ``func`` along the given axis of the
        DataFrame.

    See Also
    --------
    DataFrame.map: For elementwise operations.
    DataFrame.aggregate: Only perform aggregating type operations.
    DataFrame.transform: Only perform transforming type operations.

    Notes
    -----
    Functions that mutate the passed object can produce unexpected
    behavior or errors and are not supported. See :ref:`gotchas.udf-mutation`
    for more details.

    Examples
    --------
    >>> df = pd.DataFrame([[4, 9]] * 3, columns=['A', 'B'])
    >>> df
       A  B
    0  4  9
    1  4  9
    2  4  9

    Using a numpy universal function (in this case the same as
    ``np.sqrt(df)``):

    >>> df.apply(np.sqrt)
         A    B
    0  2.0  3.0
    1  2.0  3.0
    2  2.0  3.0

    Using a reducing function on either axis

    >>> df.apply(np.sum, axis=0)
    A    12
    B    27
    dtype: int64

    >>> df.apply(np.sum, axis=1)
    0    13
    1    13
    2    13
    dtype: int64

    Returning a list-like will result in a Series

    >>> df.apply(lambda x: [1, 2], axis=1)
    0    [1, 2]
    1    [1, 2]
    2    [1, 2]
    dtype: object

    Passing ``result_type='expand'`` will expand list-like results
    to columns of a Dataframe

    >>> df.apply(lambda x: [1, 2], axis=1, result_type='expand')
       0  1
    0  1  2
    1  1  2
    2  1  2

    Returning a Series inside the function is similar to passing
    ``result_type='expand'``. The resulting column names
    will be the Series index.

    >>> df.apply(lambda x: pd.Series([1, 2], index=['foo', 'bar']), axis=1)
       foo  bar
    0    1    2
    1    1    2
    2    1    2

    Passing ``result_type='broadcast'`` will ensure the same shape
    result, whether list-like or scalar is returned by the function,
    and broadcast it along the axis. The resulting column names will
    be the originals.

    >>> df.apply(lambda x: [1, 2], axis=1, result_type='broadcast')
       A  B
    0  1  2
    1  1  2
    2  1  2

In [100]:
orders.\
    groupby('order_status')[ 'order_id' ].\
    agg(order_count='count')

                 order_count
order_status
CANCELED                1428
CLOSED                  7556
COMPLETE               22899
ON_HOLD                 3798
PAYMENT_REVIEW           729
PENDING                 7610
PENDING_PAYMENT        15030
PROCESSING              8275
SUSPECTED_FRAUD         1558

In [101]:
orders['order_month'] = orders.apply(lambda order : order.order_date[:7],axis=1 )

In [102]:
orders['order_month']

0        2013-07
1        2013-07
2        2013-07
3        2013-07
4        2013-07
          ...
68878    2014-07
68879    2014-07
68880    2014-07
68881    2014-07
68882    2014-07
Name: order_month, Length: 68883, dtype: object

In [103]:
orders

,order_id,order_date,order_customer_id,order_status,order_month
0,1,2013-07-25 00:00:00.0,11599,CLOSED,2013-07
1,2,2013-07-25 00:00:00.0,256,PENDING_PAYMENT,2013-07
2,3,2013-07-25 00:00:00.0,12111,COMPLETE,2013-07
3,4,2013-07-25 00:00:00.0,8827,CLOSED,2013-07
4,5,2013-07-25 00:00:00.0,11318,COMPLETE,2013-07
...,...,...,...,...,...
68878,68879,2014-07-09 00:00:00.0,778,COMPLETE,2014-07
68879,68880,2014-07-13 00:00:00.0,1117,COMPLETE,2014-07
68880,68881,2014-07-19 00:00:00.0,2518,PENDING_PAYMENT,2014-07
68881,68882,2014-07-22 00:00:00.0,10000,ON_HOLD,2014-07
68882,68883,2014-07-23 00:00:00.0,5533,COMPLETE,2014-07

In [104]:
orders.\
    groupby(["order_month", "order_status"])['order_id'].\
    agg(order_count='count')

                             order_count
order_month order_status
2013-07     CANCELED                  22
            CLOSED                   161
            COMPLETE                 515
            ON_HOLD                   81
            PAYMENT_REVIEW            19
...                                  ...
2014-07     PAYMENT_REVIEW            54
            PENDING                  517
            PENDING_PAYMENT          979
            PROCESSING               561
            SUSPECTED_FRAUD          101

[117 rows x 1 columns]

In [105]:
orders.\
    groupby(["order_month", "order_status"])['order_id'].\
    agg(order_count='count').\
    reset_index()

    order_month     order_status  order_count
0       2013-07         CANCELED           22
1       2013-07           CLOSED          161
2       2013-07         COMPLETE          515
3       2013-07          ON_HOLD           81
4       2013-07   PAYMENT_REVIEW           19
..          ...              ...          ...
112     2014-07   PAYMENT_REVIEW           54
113     2014-07          PENDING          517
114     2014-07  PENDING_PAYMENT          979
115     2014-07       PROCESSING          561
116     2014-07  SUSPECTED_FRAUD          101

[117 rows x 3 columns]

In [106]:
# Joining Data in Pandas Dataframes
# Here are the steps involved in joining data using Pandas Dataframe APIs.

# First, we need to define index for both the dataframes that are supposed to be joined.
# Use join to join the Dataframes based on index. The default join is left, we need to make sure right join is used based on the requirement.
# In our case, we will join orders and customers using inner join.

import pandas as pd

In [107]:
import json

In [108]:
schemas = json.load(open('/Users/amisha/Desktop/Data_engineering/data/retail_db/schemas.json'))

In [109]:
def get_column_names(schemas,ds_name,sorting_key='column_position'):
    column_details = schemas[ds_name]
    column = sorted(column_details, key=lambda x: x[sorting_key])
    return [col['column_name'] for col in column]

In [110]:
order_columns = get_column_names(schemas,'orders')

In [111]:
order_columns

['order_id', 'order_date', 'order_customer_id', 'order_status']

In [112]:
orders = pd.read_csv('/Users/amisha/Desktop/Data_engineering/data/retail_db/orders/part-00000',
    header=None,
    names=order_columns)

In [113]:
orders

       order_id             order_date  order_customer_id     order_status
0             1  2013-07-25 00:00:00.0              11599           CLOSED
1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0              12111         COMPLETE
3             4  2013-07-25 00:00:00.0               8827           CLOSED
4             5  2013-07-25 00:00:00.0              11318         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68883 rows x 4 columns]

In [114]:
customer_columns = get_column_names(schemas,'customers')

In [115]:
customer_columns

['customer_id',
 'customer_fname',
 'customer_lname',
 'customer_email',
 'customer_password',
 'customer_street',
 'customer_city',
 'customer_state',
 'customer_zipcode']

In [116]:
customers = pd.read_csv('/Users/amisha/Desktop/Data_engineering/data/retail_db/customers/part-00000',
    header=None,
    names=customer_columns)

In [117]:
customers

,customer_id,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode
0,1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521
1,2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126
2,3,Ann,Smith,XXXXXXXXX,XXXXXXXXX,3422 Blue Pioneer Bend,Caguas,PR,725
3,4,Mary,Jones,XXXXXXXXX,XXXXXXXXX,8324 Little Common,San Marcos,CA,92069
4,5,Robert,Hudson,XXXXXXXXX,XXXXXXXXX,10 Crystal River Mall,Caguas,PR,725
...,...,...,...,...,...,...,...,...,...
12430,12431,Mary,Rios,XXXXXXXXX,XXXXXXXXX,1221 Cinder Pines,Kaneohe,HI,96744
12431,12432,Angela,Smith,XXXXXXXXX,XXXXXXXXX,1525 Jagged Barn Highlands,Caguas,PR,725
12432,12433,Benjamin,Garcia,XXXXXXXXX,XXXXXXXXX,5459 Noble Brook Landing,Levittown,NY,11756
12433,12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725
12434,12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483

In [118]:
customers.set_index('customer_id', inplace=True)

In [119]:
orders.set_index('order_customer_id', inplace=True)

In [120]:
customers_orders = customers.join(orders, how='inner')

In [121]:
customers_orders

,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode,order_id,order_date,order_status
customer_id,,,,,,,,,,,
1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521,22945,2013-12-13 00:00:00.0,COMPLETE
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,15192,2013-10-29 00:00:00.0,PENDING_PAYMENT
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,33865,2014-02-18 00:00:00.0,COMPLETE
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,57963,2013-08-02 00:00:00.0,ON_HOLD
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,67863,2013-11-30 00:00:00.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,42915,2014-04-16 00:00:00.0,COMPLETE
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,51800,2014-06-14 00:00:00.0,ON_HOLD
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,61777,2013-12-26 00:00:00.0,COMPLETE
12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483,41643,2014-04-08 00:00:00.0,PENDING
12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483,61629,2013-12-21 00:00:00.0,CANCELED

In [122]:
customers_orders. \
    reset_index(names='customer_id'). \
    groupby('customer_id')['customer_id']. \
    agg(order_count='count'). \
    reset_index(). \
    query('order_count >= 10')

       customer_id  order_count
70              71           10
171            172           10
173            174           12
196            197           11
219            221           15
...            ...          ...
12311        12341           10
12317        12347           10
12375        12406           10
12400        12431           16
12401        12432           10

[699 rows x 2 columns]

In [123]:
orders

                   order_id             order_date     order_status
order_customer_id
11599                     1  2013-07-25 00:00:00.0           CLOSED
256                       2  2013-07-25 00:00:00.0  PENDING_PAYMENT
12111                     3  2013-07-25 00:00:00.0         COMPLETE
8827                      4  2013-07-25 00:00:00.0           CLOSED
11318                     5  2013-07-25 00:00:00.0         COMPLETE
...                     ...                    ...              ...
778                   68879  2014-07-09 00:00:00.0         COMPLETE
1117                  68880  2014-07-13 00:00:00.0         COMPLETE
2518                  68881  2014-07-19 00:00:00.0  PENDING_PAYMENT
10000                 68882  2014-07-22 00:00:00.0          ON_HOLD
5533                  68883  2014-07-23 00:00:00.0         COMPLETE

[68883 rows x 3 columns]

In [124]:
orders.\
    sort_values(by=['order_customer_id'])

                   order_id             order_date     order_status
order_customer_id
1                     22945  2013-12-13 00:00:00.0         COMPLETE
2                     67863  2013-11-30 00:00:00.0         COMPLETE
2                     33865  2014-02-18 00:00:00.0         COMPLETE
2                     15192  2013-10-29 00:00:00.0  PENDING_PAYMENT
2                     57963  2013-08-02 00:00:00.0          ON_HOLD
...                     ...                    ...              ...
12434                 42915  2014-04-16 00:00:00.0         COMPLETE
12434                 13544  2013-10-16 00:00:00.0          PENDING
12434                  5303  2013-08-26 00:00:00.0          PENDING
12435                 41643  2014-04-08 00:00:00.0          PENDING
12435                 61629  2013-12-21 00:00:00.0         CANCELED

[68883 rows x 3 columns]

In [125]:
orders.\
    sort_values(by=['order_customer_id'], ascending=False)

                   order_id             order_date     order_status
order_customer_id
12435                 41643  2014-04-08 00:00:00.0          PENDING
12435                 61629  2013-12-21 00:00:00.0         CANCELED
12434                  4799  2013-08-23 00:00:00.0  PENDING_PAYMENT
12434                  5303  2013-08-26 00:00:00.0          PENDING
12434                  1868  2013-08-03 00:00:00.0           CLOSED
...                     ...                    ...              ...
2                     67863  2013-11-30 00:00:00.0         COMPLETE
2                     33865  2014-02-18 00:00:00.0         COMPLETE
2                     15192  2013-10-29 00:00:00.0  PENDING_PAYMENT
2                     57963  2013-08-02 00:00:00.0          ON_HOLD
1                     22945  2013-12-13 00:00:00.0         COMPLETE

[68883 rows x 3 columns]

In [126]:
orders.\
    sort_values(by=['order_customer_id', 'order_date'], ascending=[False, True])

                   order_id             order_date     order_status
order_customer_id
12435                 61629  2013-12-21 00:00:00.0         CANCELED
12435                 41643  2014-04-08 00:00:00.0          PENDING
12434                  1868  2013-08-03 00:00:00.0           CLOSED
12434                  4799  2013-08-23 00:00:00.0  PENDING_PAYMENT
12434                  5303  2013-08-26 00:00:00.0          PENDING
...                     ...                    ...              ...
2                     57963  2013-08-02 00:00:00.0          ON_HOLD
2                     15192  2013-10-29 00:00:00.0  PENDING_PAYMENT
2                     67863  2013-11-30 00:00:00.0         COMPLETE
2                     33865  2014-02-18 00:00:00.0         COMPLETE
1                     22945  2013-12-13 00:00:00.0         COMPLETE

[68883 rows x 3 columns]

In [134]:
import os
os.makedirs('/Users/amisha/Desktop/Data_engineering/output/retail_db/output_json', exist_ok=True)

In [135]:
# Stores using columnar format
# Review data in the files to understand how data is formatted
# orders.to_json('/Users/amisha/Desktop/Data_engineering/data/retail_db/output_json/part-00000')

In [136]:
# Save data using row format
orders.to_json(
    '/Users/amisha/Desktop/Data_engineering/output/retail_db/output_json/part-00000',
    orient='records',
    lines=True
)

In [137]:
pd.read_json('/Users/amisha/Desktop/Data_engineering/output/retail_db/output_json/part-00000',
    lines=True
)

       order_id             order_date     order_status
0             1  2013-07-25 00:00:00.0           CLOSED
1             2  2013-07-25 00:00:00.0  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0         COMPLETE
3             4  2013-07-25 00:00:00.0           CLOSED
4             5  2013-07-25 00:00:00.0         COMPLETE
...         ...                    ...              ...
68878     68879  2014-07-09 00:00:00.0         COMPLETE
68879     68880  2014-07-13 00:00:00.0         COMPLETE
68880     68881  2014-07-19 00:00:00.0  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0          ON_HOLD
68882     68883  2014-07-23 00:00:00.0         COMPLETE

[68883 rows x 3 columns]

In [138]:
pd.read_json('/Users/amisha/Desktop/Data_engineering/output/retail_db/output_json/part-00000',
    lines=True
)

       order_id             order_date     order_status
0             1  2013-07-25 00:00:00.0           CLOSED
1             2  2013-07-25 00:00:00.0  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0         COMPLETE
3             4  2013-07-25 00:00:00.0           CLOSED
4             5  2013-07-25 00:00:00.0         COMPLETE
...         ...                    ...              ...
68878     68879  2014-07-09 00:00:00.0         COMPLETE
68879     68880  2014-07-13 00:00:00.0         COMPLETE
68880     68881  2014-07-19 00:00:00.0  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0          ON_HOLD
68882     68883  2014-07-23 00:00:00.0         COMPLETE

[68883 rows x 3 columns]